### **Understanding Numpy**

- Numpy (Numerical Python) is the foundation library for scientific computing in python. It provides N-dimensional array object and tools for working with these arrays.
- Think of NumPy as the engine that powers most data science libraries - pandas uses NumPy arrarys internally, scikit-learn expects NumPy arrays for machine learning, and matplotlib uses NumPy for plotting.
- NumPy operations are implemented in C, making them 10-100x faster than pure Python.
- NumPy arrays store data more compactly than python lists.
- Vectorization: Perform operations on entire arrays without writing loops.
- Work with arrays of different shapes seamlessly.
- Foundation for pandas, scikit-learn, matplotlib, and more.

In [2]:
# import all necessary libraries

import numpy as np
import matplotlib.pyplot as plt
import time

# Check NumPy version 
print(f"Numpy version: {np.__version__}")

# Display settings for cleaner output
np.set_printoptions(precision=3, suppress=True)


Numpy version: 2.3.2


* Creating Numpy Arrays

In [3]:
# Creating arrays from python lists
# 1D array: A simple sequence of numbers
arr1d = np.array([1, 2, 3, 4, 5])

# 2D array: Think of this as a matrix or table with rows and columns
arr2d = np.array([[1,2,3],
                  [4,5,6]])

# 3D array: Like a stack of 2D arrays - useful for images, time series, etc.
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5,6], [7, 8]]])

print("1D arrays:", arr1d)
print("2D array:\n", arr2d)
print("3D array:\n", arr3d)

1D arrays: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Creating Special Arrays in Numpy

In [4]:
# Creating arrays filled with zeros - useful for initializing arrays
zeros = np.zeros((3,4))

# Creating arrays filled with ones - often used as starting points
ones = np.ones((2, 3, 4))   # 3D array: 2 layers, 3 rows, 4 columns

# Empty array - faster than zeros/ones but contains random values
empty = np.empty((2, 2))

print("Zeros array (3x4):\n", zeros) 
print("Ones array shape:", ones.shape)
print("Empty array (contains random values):\n", empty)

Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array shape: (2, 3, 4)
Empty array (contains random values):
 [[0. 0.]
 [0. 0.]]


In [5]:
# Range arrays - like python's range() but more powerful
range_arr = np.arange(0, 10, 2)
print("Range array:", range_arr)

# Linearly spaced arrays
linspace_arr = np.linspace(0, 1, 5)
print("Linspace array:", linspace_arr)

# Logarithmically spaced arrays
logspace_arr = np.logspace(0, 2, 5)
print("Logspace array:", logspace_arr)

Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
Logspace array: [  1.      3.162  10.     31.623 100.   ]


In [6]:
identity = np.eye(4)
diagonal = np.diag([1, 2, 3, 4])
full_arr = np.full((3, 3), 7)

print("Identity matrix:\n", identity)
print("Diagonal matrix:\n", diagonal)
print("Full array (filled with 7):\n", full_arr)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


#### Numpy Data Types (dtypes)

In [7]:
int_arr = np.array([1, 2, 3], dtype=np.int32)
float_arr = np.array([1, 2, 3], dtype=np.float64)
bool_arr = np.array([True, False, True], dtype=np.bool_)
converted = int_arr.astype(np.float32)

print("Integer array dtype:", int_arr.dtype)
print("Float array dtype:", float_arr.dtype)
print("Boolean array dtype:", bool_arr.dtype)
print("Converted array dtype:", converted.dtype)

print(f"int32 uses {int_arr.itemsize} bytes per element")
print(f"float64 uses {float_arr.itemsize} bytes per element")

Integer array dtype: int32
Float array dtype: float64
Boolean array dtype: bool
Converted array dtype: float32
int32 uses 4 bytes per element
float64 uses 8 bytes per element


#### Array Properties & Attributes
- Understanding array properties helps you work effectively with your data and debug issues

In [8]:
# Create a sample 3D array for demonstration
arr = np.random.randn(3, 4, 5)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Ndim:", arr.ndim)
print("Dtype:", arr.dtype)          
print("Itemsize:", arr.itemsize)     

# Total memory usage in bytes
print("Memory usage:", arr.nbytes, "bytes")  
print("Memory usage:", arr.nbytes / 1024, "KB")  # Convert to KB

Shape: (3, 4, 5)
Size: 60
Ndim: 3
Dtype: float64
Itemsize: 8
Memory usage: 480 bytes
Memory usage: 0.46875 KB


These properties are essential for understanding your data's structure and memory requirements. Large datasets require careful attention to memory usage.

**Array Indexing & Slicing**

 **Basic Indexing - Accessing Individual Elements**

- NumPy indexing is similar to Python lists but more powerful for multi-dimensional arrays

In [9]:
# 1D array indexing - similar to Python lists
arr1d = np.array([10, 20, 30, 40, 50])

print("First element:", arr1d[0])     # Index 0: 10
print("Last element:", arr1d[-1])     # Negative indexing: 50  
print("Slice [1:4]:", arr1d[1:4])     # Elements 1, 2, 3: [20, 30, 40]
print("Every 2nd element:", arr1d[::2])  # Step of 2: [10, 30, 50]

First element: 10
Last element: 50
Slice [1:4]: [20 30 40]
Every 2nd element: [10 30 50]


Negative indices count from the end (-1 is last element). Slicing uses [start:stop:step] where stop is exclusive.

In [10]:
# 2D array indexing - row and column access
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Access specific element: [row, column]
print("Element at row 1, column 2:", arr2d[1, 2])        # 7

# Access entire rows or columns
print("First row:", arr2d[0, :])               # All columns of row 0
print("Second column:", arr2d[:, 1])           # All rows of column 1

# Subarray slicing: [row_start:row_end, col_start:col_end]
print("Subarray (rows 1-2, cols 1-2):\n", arr2d[1:3, 1:3])

Element at row 1, column 2: 7
First row: [1 2 3 4]
Second column: [ 2  6 10]
Subarray (rows 1-2, cols 1-2):
 [[ 6  7]
 [10 11]]


The comma separates dimensions. : means "all elements along this dimension". Slicing creates views of the original data when possible, not copies.

**Advanced Indexing - Powerful Selection Methods**

In [11]:
# Fancy indexing - use arrays of indices to select elements
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4])  # Select elements at positions 0, 2, 4
print("Fancy indexing:", arr[indices])         # [10, 30, 50]

# This is much more flexible than simple slicing
random_indices = np.array([4, 1, 3, 1])  # Can repeat and reorder
print("Random order:", arr[random_indices])   # [50, 20, 40, 20]

Fancy indexing: [10 30 50]
Random order: [50 20 40 20]


Fancy indexing lets you select elements in any order, repeat elements, and select non-contiguous elements. Very useful for data sampling and reordering.

In [12]:
# 2D fancy indexing - select specific row/column combinations
arr2d = np.arange(12).reshape(3, 4)  # 3x4 array: [[0,1,2,3], [4,5,6,7], [8,9,10,11]]
print("Original 2D array:\n", arr2d)

# Select elements at (row, col) pairs: (0,1) and (2,3)
rows = np.array([0, 2])
cols = np.array([1, 3])
print("Elements at (0,1) and (2,3):", arr2d[rows, cols])  # [1, 11]

# Select entire rows using fancy indexing
selected_rows = arr2d[[0, 2], :]  # Rows 0 and 2, all columns
print("Selected rows:\n", selected_rows)

Original 2D array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Elements at (0,1) and (2,3): [ 1 11]
Selected rows:
 [[ 0  1  2  3]
 [ 8  9 10 11]]


When you provide arrays for both dimensions, NumPy pairs them element-wise. This is different from slicing, which creates a rectangular subarray.

**Array Reshaping & Manipulation**

- Reshaping changes how the same data is organized in memory without changing the actual values.

In [13]:
# Start with a 1D array
arr = np.arange(12)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
print("Original 1D array:", arr)

# Reshape to 2D: 3 rows × 4 columns
reshaped_2d = arr.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped_2d)

# Reshape to 3D: 2 layers × 2 rows × 3 columns  
reshaped_3d = arr.reshape(2, 2, 3)
print("Reshaped to 2x2x3:\n", reshaped_3d)

# Use -1 to let NumPy calculate one dimension automatically
auto_reshape = arr.reshape(4, -1)  # 4 rows, NumPy calculates columns
print("Auto-reshaped to 4x?:\n", auto_reshape)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x2x3:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Auto-reshaped to 4x?:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The total number of elements must remain the same (12 in this case). Using -1 tells NumPy to calculate that dimension automatically. Reshaping creates a view when possible, not a copy

In [14]:
# Flattening - convert multi-dimensional array to 1D
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# flatten() always returns a copy
flattened = arr2d.flatten()                 
print("Flattened (copy):", flattened)

# ravel() returns a view if possible (faster, memory efficient)
ravel = arr2d.ravel()                       
print("Ravel (view if possible):", ravel)

# Demonstrate the difference
arr2d[0, 0] = 999
print("After modifying original:")
print("Flattened (unchanged):", flattened)  # Copy is independent
print("Ravel (changed):", ravel)  

Flattened (copy): [1 2 3 4 5 6]
Ravel (view if possible): [1 2 3 4 5 6]
After modifying original:
Flattened (unchanged): [1 2 3 4 5 6]
Ravel (changed): [999   2   3   4   5   6]


Use ravel() when you don't need to modify the flattened array independently. Use flatten() when you need a separate copy that won't be affected by changes to the original.

**Transposing and Swapping Axes**

 - Transposing is essential for matrix operations and changing data orientation

In [15]:
# 2D transposition - flip rows and columns
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6]])
print("Original shape:", arr2d.shape)      # (2, 3)
print("Original:\n", arr2d)

print("Transposed shape:", arr2d.T.shape)   # (3, 2)
print("Transposed:\n", arr2d.T)

# Alternative transpose methods
print("Transpose method:\n", arr2d.transpose())

Original shape: (2, 3)
Original:
 [[1 2 3]
 [4 5 6]]
Transposed shape: (3, 2)
Transposed:
 [[1 4]
 [2 5]
 [3 6]]
Transpose method:
 [[1 4]
 [2 5]
 [3 6]]


Transposing swaps rows and columns. This is crucial for matrix multiplication and when you need to change data orientation (e.g., from samples×features to features×samples)

In [16]:
# Higher-dimensional transposition
arr3d = np.arange(24).reshape(2, 3, 4)  # 2 layers, 3 rows, 4 columns
print("Original 3D shape:", arr3d.shape)

# Specify new axis order: (axis0, axis1, axis2) → (axis2, axis0, axis1)
transposed_3d = arr3d.transpose(2, 0, 1)
print("Transposed 3D shape:", transposed_3d.shape)  # (4, 2, 3)

# moveaxis is another way to rearrange axes
moved = np.moveaxis(arr3d, 0, -1)  # Move first axis to last position
print("Moveaxis result shape:", moved.shape)

Original 3D shape: (2, 3, 4)
Transposed 3D shape: (4, 2, 3)
Moveaxis result shape: (3, 4, 2)


For 3D+ arrays, you specify the new order of axes. This is useful for reshaping data for different algorithms or visualization requirements.

**Concatenating and Splitting Arrays**

- Combining and dividing arrays is fundamental for data manipulation

In [17]:
# Concatenation - joining arrays along existing axes
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along different axes
concat_rows = np.concatenate([arr1, arr2], axis=0)    # Stack vertically (add rows)
concat_cols = np.concatenate([arr1, arr2], axis=1)    # Stack horizontally (add columns)

print("Original arrays:")
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Concatenated vertically (axis=0):\n", concat_rows)
print("Concatenated horizontally (axis=1):\n", concat_cols)

Original arrays:
Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Concatenated vertically (axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated horizontally (axis=1):
 [[1 2 5 6]
 [3 4 7 8]]


`axis=0` means along rows (vertical stacking), `axis=1` means along columns (horizontal stacking). Arrays must have compatible shapes along the non-concatenated dimensions.

In [18]:
# Convenient stacking functions
vstack_result = np.vstack([arr1, arr2])     # Same as concatenate with axis=0
hstack_result = np.hstack([arr1, arr2])     # Same as concatenate with axis=1
dstack_result = np.dstack([arr1, arr2])     # Stack along depth (3rd dimension)

print("vstack (vertical):\n", vstack_result)
print("hstack (horizontal):\n", hstack_result)
print("dstack shape:", dstack_result.shape)  # Creates 3D array

# Splitting arrays - opposite of concatenation
arr = np.arange(12).reshape(3, 4)
split_arrays = np.split(arr, 3, axis=0)        # Split into 3 parts along rows
print("Original array for splitting:\n", arr)
print("Split into 3 parts along rows:")
for i, split_part in enumerate(split_arrays):
    print(f"Part {i}:\n", split_part)

vstack (vertical):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack (horizontal):
 [[1 2 5 6]
 [3 4 7 8]]
dstack shape: (2, 2, 2)
Original array for splitting:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Split into 3 parts along rows:
Part 0:
 [[0 1 2 3]]
Part 1:
 [[4 5 6 7]]
Part 2:
 [[ 8  9 10 11]]


Stacking functions are shortcuts for concatenation. Splitting divides an array into equal parts - useful for creating training/validation sets or processing data in chunks.

**Mathematical Operations**

**Element-wise Operations - The Power of Vectorization**

- NumPy's biggest advantage is performing operations on entire arrays without writing loo

In [19]:
# Basic arithmetic operations work element-by-element
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

print("Array 1:", arr1)
print("Array 2:", arr2)

# All operations happen element-wise automatically
print("Addition:", arr1 + arr2)               # [11, 22, 33, 44]
print("Subtraction:", arr2 - arr1)            # [9, 18, 27, 36]
print("Multiplication:", arr1 * arr2)         # [10, 40, 90, 160]
print("Division:", arr2 / arr1)               # [10, 10, 10, 10]
print("Power:", arr1 ** 2)                    # [1, 4, 9, 16]
print("Modulo:", arr2 % 3)    

Array 1: [1 2 3 4]
Array 2: [10 20 30 40]
Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [ 1  4  9 16]
Modulo: [1 2 0 1]


This vectorization is much faster than Python loops because the operations are implemented in optimized C code. Each operation applies to corresponding elements.

In [20]:
# Operations with scalars - broadcasting in action
print("Scalar operations:")
print("Add 10 to all elements:", arr1 + 10)          # [11, 12, 13, 14]
print("Multiply all by 3:", arr1 * 3)               # [3, 6, 9, 12]
print("Divide all by 2:", arr1 / 2)                 # [0.5, 1, 1.5, 2]

# Compound operations
result = (arr1 + 5) * 2 - 1                         # ((arr1 + 5) * 2) - 1
print("Compound operation (arr1 + 5) * 2 - 1:", result)

Scalar operations:
Add 10 to all elements: [11 12 13 14]
Multiply all by 3: [ 3  6  9 12]
Divide all by 2: [0.5 1.  1.5 2. ]
Compound operation (arr1 + 5) * 2 - 1: [11 13 15 17]


When you operate on arrays with scalars, the scalar is automatically "broadcast" to match the array shape. This is much more readable and efficient than manual loops

**Mathematical Functions - Beyond Basic Arithmetic**

- NumPy provides vectorized versions of most mathematical function

In [21]:
# Common mathematical functions
arr = np.array([1, 4, 9, 16, 25])
print("Original array:", arr)

# Square roots and powers
print("Square root:", np.sqrt(arr))           # [1, 2, 3, 4, 5]
print("Square:", np.square(arr))              # [1, 16, 81, 256, 625]
print("Cube root:", np.cbrt(arr))

# Exponential and logarithmic functions
small_arr = np.array([1, 2, 3])
print("Exponential:", np.exp(small_arr))      # [e^1, e^2, e^3]
print("Natural log:", np.log(arr))            # ln(arr)
print("Log base 10:", np.log10(arr))
print("Log base 2:", np.log2(arr))

Original array: [ 1  4  9 16 25]
Square root: [1. 2. 3. 4. 5.]
Square: [  1  16  81 256 625]
Cube root: [1.    1.587 2.08  2.52  2.924]
Exponential: [ 2.718  7.389 20.086]
Natural log: [0.    1.386 2.197 2.773 3.219]
Log base 10: [0.    0.602 0.954 1.204 1.398]
Log base 2: [0.    2.    3.17  4.    4.644]


These functions are much faster than applying Python's math functions in a loop. They also handle edge cases (like log of zero) more gracefully.